/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface WatchOptions {
  script: string
  ext?: string
  ignore?: Array<string>
  exec?: string
  delay?: number
}
export declare function watch(options: WatchOptions): void
